### ISSUE TITLE
Tune PID constants for swerve modules from the Shuffleboard

### ISSUE THREAD

**Issue by calebur** [Manchester-Central/2022-Rapid-React#16]
It would be convenient to adjust the PID constants for swerve module Angle and Velocity control from the Shuffleboard

**Comment by croooutons** [comment]
[Change made here](https://github.com/Manchester-Central/2022-Rapid-React/commit/abbf6ebe364e808c238148fed98cdcd34d1a6b22)

**Comment by calebur** [comment]
There's a bug in this: https://github.com/Manchester-Central/2022-Rapid-React/blob/abbf6ebe364e808c238148fed98cdcd34d1a6b22/src/main/java/frc/robot/subsystems/SwerveDriveModule.java#L128-L130
