### ISSUE TITLE
Add support for NavX gyroscope

### ISSUE THREAD

**Issue by calebur** [Manchester-Central/2022-Rapid-React#17]
Product documentation: https://www.kauailabs.com/navx-mxp/ and https://pdocs.kauailabs.com/navx-mxp/wp-content/uploads/2020/09/navx2-mxp_robotics_navigation_sensor_user_guide-8.pdf

There is a calibration period when the device turns on, maybe this should be displayed on the Shuffleboard so we can tell when the robot should not be moved.  See: https://www.kauailabs.com/public_files/navx-mxp/apidocs/java/com/kauailabs/navx/frc/AHRS.html#isCalibrating()

**Comment by acezyx** [comment]
We worked on this together https://github.com/Manchester-Central/2022-Rapid-React/commit/5b04f12b9db82e89fe7dd427c549da6a2dabd5f9
