### ISSUE TITLE
Isolate Simulation code in SwerveDrive

### ISSUE THREAD

**Issue by jnallard** [Manchester-Central/2022-Rapid-React#18]
We should update the SwerveDrive and SwerveDriveModule code to only do the fake simulation updates when in the simulator. When not in the simulator, we should use the actual sensor values.

We can do this by taking advantage of `SimulationPeriodic()` or `!RobotBase.isReal()`.

Making this change will make it easier to go back and forth from the simulator and the real robot. 

We can also do similar things with the other subsystems.

Refs:
https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-simulation/drivesim-tutorial/index.html
https://www.kauailabs.com/navx-mxp/

**Comment by NinjaBuilderPro** [comment]
We worked on this together. https://github.com/Manchester-Central/2022-Rapid-React/commit/8740fc305665124634da203e1377bd08124c50fb
