### ISSUE TITLE
Update Swerve Module to have absolute encoders for angle

### ISSUE THREAD

**Issue by jnallard** [Manchester-Central/2022-Rapid-React#20]
We are waiting the hardware for absolute encoders on the CAN bus to help control the angle of each Swerve Module

We can use this for setting up the close loop for the absolute sensor:
https://docs.ctre-phoenix.com/en/stable/ch16_ClosedLoop.html#closed-loop-configurations

**Comment by calebur** [comment]
This change is tracked in #25.
