### ISSUE TITLE
Update to swerveDriveModuleOffset actual robot data

### ISSUE THREAD

**Issue by tri-vu-12** [Manchester-Central/2022-Rapid-React#21]

**Comment by jnallard** [comment]
For reference, these are the values we want to update from arbitrary values:
https://github.com/Manchester-Central/2022-Rapid-React/pull/19/files#r799093655

**Comment by calebur** [comment]
Note: Issue #25 adds absolute encoders, which can be zeroed to an arbitrary location.  This issue is intertwined with the calibration of #25.

**Comment by jnallard** [comment]
We finished this yesterday with the students. See #53
