### ISSUE TITLE
CANifier for swerve module angle encoders

### ISSUE THREAD

**Issue by calebur** [Manchester-Central/2022-Rapid-React#25]
We will be getting 4x [CANifier](https://store.ctr-electronics.com/canifier/) to connect the angle encoders to the CAN bus.

API Reference: https://store.ctr-electronics.com/content/api/java/html/classcom_1_1ctre_1_1phoenix_1_1_c_a_nifier.html

**Comment by calebur** [comment]
https://wcproducts.info/files/frc/manuals/WCP%20Swerve%20X%20-%20User%20Guide.pdf

**Comment by jnallard** [comment]
We ended up swapping these with CANcoders: #53, but it's done and working now
