### ISSUE TITLE
Add Logging Without Network Tables

### ISSUE THREAD

**Issue by jnallard** [Manchester-Central/2022-Rapid-React#4]
We noticed in past years that if we log too much to Network Tables, we see connection issues with the robot during competition matches. 
We should develop a logging function that will let us log to a file (such as a USB plugged into the RIO) that will not usurp network capacity. 
Might be good to have a way to log to both, so we can use network tables when debugging, but disable during competition matches.

**Comment by calebur** [comment]
Pull request #13 added logging functionality.  

It still need to be tested on the RoboRIO.

Writing to the underlying file could be moved to a separate thread to avoid any potential blocking of robot control code.

TBD: Should a something like `fsync` be performed (and at what interval?) to ensure loss of power doesn't loose too much of the data?

**Comment by calebur** [comment]
Pull request #78 completed this feature
